-- AddColumn maintenance mode + feature flags
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "maintenanceMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "featConfirmationEmail" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "featBotReply" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "featAiAnalysis" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "featCsatSurvey" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AppConfig" ADD COLUMN IF NOT EXISTS "featGithubIssueCreation" BOOLEAN NOT NULL DEFAULT true;
