/* eslint-disable no-console */
/**
 * scripts/atlas-gen.ts
 *
 * Regenerates the auto-generated half of docs/atlas/:
 *   - api-routes.md   — every Nest controller's endpoints, grouped per module
 *   - erd.md          — Mermaid erDiagram from prisma/schema.prisma
 *   - module-graph.md — Mermaid flowchart of NestJS module imports
 *
 * Run: `pnpm atlas:gen` (from repo root).
 */
import { Project, SyntaxKind, type ClassDeclaration, type Decorator } from 'ts-morph'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, basename, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..')
const OUT_DIR = join(REPO_ROOT, 'docs', 'atlas', '_generated')
const API_SRC = join(REPO_ROOT, 'apps', 'api', 'src')
const PRISMA_SCHEMA = join(REPO_ROOT, 'packages', 'db', 'prisma', 'schema.prisma')
const GLOBAL_PREFIX = '/api/v1'

mkdirSync(OUT_DIR, { recursive: true })

const HEADER = (kind: string): string =>
  `<!-- AUTO-GENERATED by scripts/atlas-gen.ts — DO NOT EDIT BY HAND -->\n` +
  `<!-- Run \`pnpm atlas:gen\` to refresh -->\n` +
  `_Last generated: ${new Date().toISOString()}_\n\n` +
  `# ${kind}\n\n`

// ─── helpers ────────────────────────────────────────────────────────────────

function unquote(s: string): string {
  return s.replace(/^['"`]/, '').replace(/['"`]$/, '')
}

function firstStringArg(dec: Decorator): string | null {
  const args = dec.getArguments()
  for (const a of args) {
    if (a.getKind() === SyntaxKind.StringLiteral || a.getKind() === SyntaxKind.NoSubstitutionTemplateLiteral) {
      return unquote(a.getText())
    }
  }
  return null
}

function joinPath(prefix: string, route: string | null): string {
  const left = `${GLOBAL_PREFIX}/${prefix}`.replace(/\/+/g, '/')
  if (!route) return left.replace(/\/$/, '') || '/'
  return `${left}/${route}`.replace(/\/+/g, '/').replace(/\/$/, '') || '/'
}

// ─── 1. API routes ──────────────────────────────────────────────────────────

interface RouteEntry {
  method: string
  path: string
  handler: string
}

function generateApiRoutes(): void {
  const project = new Project({
    tsConfigFilePath: join(REPO_ROOT, 'apps', 'api', 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  })
  project.addSourceFilesAtPaths(`${API_SRC}/modules/**/*.controller.ts`)

  const HTTP_DECORATORS = new Set(['Get', 'Post', 'Put', 'Patch', 'Delete', 'Head', 'Options', 'All'])
  const byController = new Map<string, { prefix: string; file: string; routes: RouteEntry[] }>()

  for (const sf of project.getSourceFiles()) {
    for (const cls of sf.getClasses()) {
      const ctrlDec = cls.getDecorator('Controller')
      if (!ctrlDec) continue
      const prefix = firstStringArg(ctrlDec) ?? ''
      const name = cls.getName() ?? '(anonymous)'
      const relPath = sf.getFilePath().replace(`${REPO_ROOT}/`, '')
      const routes: RouteEntry[] = []

      for (const method of cls.getMethods()) {
        for (const dec of method.getDecorators()) {
          const decName = dec.getName()
          if (!HTTP_DECORATORS.has(decName)) continue
          routes.push({
            method: decName.toUpperCase(),
            path: joinPath(prefix, firstStringArg(dec)),
            handler: method.getName(),
          })
        }
      }
      if (routes.length === 0) continue
      byController.set(name, { prefix, file: relPath, routes })
    }
  }

  const sortedNames = [...byController.keys()].sort()
  let md = HEADER('API routes')
  md += `Each Nest controller's HTTP endpoints. Global prefix \`${GLOBAL_PREFIX}\`.\n\n`

  for (const name of sortedNames) {
    const entry = byController.get(name)!
    md += `## ${name}\n\n`
    md += `> [\`${entry.file}\`](../../../${entry.file})\n\n`
    md += `| Method | Path | Handler |\n|---|---|---|\n`
    for (const r of entry.routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))) {
      md += `| ${r.method} | \`${r.path}\` | \`${r.handler}\` |\n`
    }
    md += '\n'
  }

  const total = [...byController.values()].reduce((s, e) => s + e.routes.length, 0)
  md += `\n_Total: **${total} routes** across **${byController.size} controllers**._\n`

  writeFileSync(join(OUT_DIR, 'api-routes.md'), md)
  console.log(`  ✓ api-routes.md — ${total} routes across ${byController.size} controllers`)
}

// ─── 2. Module graph ────────────────────────────────────────────────────────

interface ModuleEntry {
  name: string
  imports: string[]
  providers: string[]
  exports: string[]
  isGlobal: boolean
}

function generateModuleGraph(): void {
  const project = new Project({ skipAddingFilesFromTsConfig: true })
  project.addSourceFilesAtPaths(`${API_SRC}/**/*.module.ts`)

  const modules: ModuleEntry[] = []

  for (const sf of project.getSourceFiles()) {
    for (const cls of sf.getClasses()) {
      const modDec = cls.getDecorator('Module')
      if (!modDec) continue
      const name = cls.getName() ?? basename(sf.getFilePath()).replace('.module.ts', '')
      const arg = modDec.getArguments()[0]
      if (!arg || arg.getKind() !== SyntaxKind.ObjectLiteralExpression) continue

      const obj = arg.asKindOrThrow(SyntaxKind.ObjectLiteralExpression)
      const grab = (prop: string): string[] => {
        const p = obj.getProperty(prop)
        if (!p) return []
        const initializer = p.getFirstDescendantByKind(SyntaxKind.ArrayLiteralExpression)
        if (!initializer) return []
        return initializer.getElements()
          .map((e) => {
            // Strip trailing `(...)` (multi-line aware) so `ConfigModule.forRoot({...})` → `ConfigModule.forRoot`
            let s = e.getText().replace(/\s+/g, ' ').replace(/\([^]*\)$/, '').trim()
            s = s.replace(/^new\s+/, '')
            // Match the first identifier — the class name. Drops `.forRoot`, `.registerQueue`, etc.
            const m = /^([A-Za-z_$][A-Za-z0-9_$]*)/.exec(s)
            return m?.[1] ?? ''
          })
          .filter((s) => s && /^[A-Z]/.test(s))
      }

      modules.push({
        name,
        imports: grab('imports'),
        providers: grab('providers'),
        exports: grab('exports'),
        isGlobal: !!cls.getDecorator('Global'),
      })
    }
  }

  modules.sort((a, b) => a.name.localeCompare(b.name))

  let md = HEADER('Module graph')
  md += `NestJS module imports across \`apps/api\`. Edges go from the module declaring an \`imports: [...]\` entry to the module being imported.\n\n`
  md += '```mermaid\nflowchart LR\n'
  for (const m of modules) {
    const label = m.isGlobal ? `${m.name}((global))` : m.name
    if (m.imports.length === 0) {
      md += `  ${m.name}["${label}"]\n`
    }
    for (const imp of m.imports) {
      md += `  ${m.name} --> ${imp}\n`
    }
  }
  md += '```\n\n'

  md += `## Modules\n\n`
  md += `| Module | Global | Imports | Providers | Exports |\n|---|---|---|---|---|\n`
  for (const m of modules) {
    md += `| \`${m.name}\` | ${m.isGlobal ? '✓' : ''} | ${m.imports.join(', ') || '—'} | ${m.providers.length} | ${m.exports.length} |\n`
  }
  md += `\n_Total: **${modules.length} modules** (${modules.filter((m) => m.isGlobal).length} global)._\n`

  writeFileSync(join(OUT_DIR, 'module-graph.md'), md)
  console.log(`  ✓ module-graph.md — ${modules.length} modules (${modules.filter((m) => m.isGlobal).length} global)`)
}

// ─── 3. Prisma ERD ──────────────────────────────────────────────────────────

interface PrismaField {
  name: string
  type: string
  isOptional: boolean
  isList: boolean
  isRelation: boolean
  attributes: string
}

interface PrismaModel {
  name: string
  fields: PrismaField[]
}

interface PrismaRelation {
  from: string
  to: string
  fromField: string
  cardinality: '||--o{' | '||--||' | '}o--o{'
}

function parsePrismaSchema(source: string): { models: PrismaModel[]; enums: { name: string; values: string[] }[] } {
  const models: PrismaModel[] = []
  const enums: { name: string; values: string[] }[] = []

  const lines = source.split('\n')
  let i = 0
  while (i < lines.length) {
    const line = lines[i].trim()
    const modelMatch = /^model\s+(\w+)\s*\{/.exec(line)
    const enumMatch = /^enum\s+(\w+)\s*\{/.exec(line)

    if (modelMatch) {
      const name = modelMatch[1]
      const fields: PrismaField[] = []
      i++
      while (i < lines.length && !lines[i].trim().startsWith('}')) {
        const fl = lines[i].trim()
        if (fl && !fl.startsWith('//') && !fl.startsWith('@@')) {
          const m = /^(\w+)\s+(\S+)(.*)$/.exec(fl)
          if (m) {
            const fname = m[1]
            const rawType = m[2]
            const rest = m[3] ?? ''
            const isList = rawType.endsWith('[]')
            const isOptional = rawType.endsWith('?')
            const baseType = rawType.replace(/[?\[\]]/g, '')
            const isRelation = /^[A-Z]/.test(baseType[0] ?? '')
            fields.push({
              name: fname, type: baseType, isOptional, isList,
              isRelation: isRelation && !['Boolean', 'String', 'Int', 'BigInt', 'Float', 'Decimal', 'DateTime', 'Json', 'Bytes'].includes(baseType),
              attributes: rest.trim(),
            })
          }
        }
        i++
      }
      models.push({ name, fields })
    } else if (enumMatch) {
      const name = enumMatch[1]
      const values: string[] = []
      i++
      while (i < lines.length && !lines[i].trim().startsWith('}')) {
        const fl = lines[i].trim()
        if (fl && !fl.startsWith('//')) values.push(fl)
        i++
      }
      enums.push({ name, values })
    }
    i++
  }

  return { models, enums }
}

function generateErd(): void {
  const source = readFileSync(PRISMA_SCHEMA, 'utf8')
  const { models, enums } = parsePrismaSchema(source)
  const modelNames = new Set(models.map((m) => m.name))

  // Build relations: only emit once per pair (model with FK references the other)
  const relations: PrismaRelation[] = []
  const seenPairs = new Set<string>()
  for (const m of models) {
    for (const f of m.fields) {
      if (!f.isRelation || !modelNames.has(f.type)) continue
      const key = [m.name, f.type].sort().join('||')
      if (seenPairs.has(key)) continue
      // Skip back-references (the other side will have an FK)
      const hasIdField = f.attributes.includes('@relation') || m.fields.some((ff) => ff.name === `${f.name}Id`)
      if (!hasIdField && !f.isList) continue
      seenPairs.add(key)
      const cardinality = f.isList ? '||--o{' : '||--||'
      relations.push({ from: f.type, to: m.name, fromField: f.name, cardinality })
    }
  }

  let md = HEADER('Database ERD')
  md += `Generated from \`packages/db/prisma/schema.prisma\`.\n\n`

  md += '```mermaid\nerDiagram\n'
  for (const m of models) {
    md += `  ${m.name} {\n`
    for (const f of m.fields) {
      if (f.isRelation) continue
      const t = f.type + (f.isList ? '[]' : '') + (f.isOptional ? '?' : '')
      const flags = f.attributes.includes('@id') ? ' PK' : f.attributes.includes('@unique') ? ' UK' : ''
      md += `    ${t} ${f.name}${flags}\n`
    }
    md += `  }\n`
  }
  md += '\n'
  for (const r of relations) {
    md += `  ${r.from} ${r.cardinality} ${r.to} : "${r.fromField}"\n`
  }
  md += '```\n\n'

  // Enum summary
  if (enums.length) {
    md += `## Enums\n\n`
    for (const e of enums) {
      md += `**\`${e.name}\`**: ${e.values.map((v) => `\`${v}\``).join(' · ')}\n\n`
    }
  }

  md += `\n_${models.length} models, ${enums.length} enums._\n`

  writeFileSync(join(OUT_DIR, 'erd.md'), md)
  console.log(`  ✓ erd.md — ${models.length} models, ${enums.length} enums`)
}

// ─── main ───────────────────────────────────────────────────────────────────

console.log('Atlas generator running...\n')
try {
  generateApiRoutes()
  generateModuleGraph()
  generateErd()
  console.log(`\nWrote to ${OUT_DIR.replace(`${REPO_ROOT}/`, '')}/`)
} catch (err) {
  console.error('atlas-gen failed:', err)
  process.exit(1)
}
